app:
  name: ui
  image:
    repository: 'onecx-apps/onecx-<%= fileName %>-ui'
  routing:
    enabled: true
    path: /mfe/<%= propertyName %>/
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './OneCX<%= remoteModuleName %>Module'        
          shareScope: angular_21       
          description: 'OneCX <%= remoteModuleName %> UI'
          note: 'OneCX <%= remoteModuleName %> UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: <%= remoteModuleFileName %>
          tagName: ocx-<%= remoteModuleFileName %>-component
    # Microservice
    microservice:
      spec:
        name: OneCX <%= remoteModuleName %> UI
        description: OneCX <%= remoteModuleName %> Frontend
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
        # ACTION P: Adjust permissions for the entity
